import { Footer } from '@components/global/Footer'
import { Header } from '@components/global/Header'
import { Seo } from '@components/global/Seo'

interface LayoutProps {
  children?: any
}

export const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Seo
        title="Create Next App"
        description="Generated by create next app"
        favicon="/favicon.ico"
      />
      <a className="skip-to-content" href="#main-content">
        Skip to content
      </a>
      <Header />
      <main id="main-content">{children}</main>
      <Footer />
    </>
  )
}
