#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Pre-Commit ✅"

yarn check-format

# Check ESLint Standards
yarn check-lint ||
(
  echo 'Found some lint that needs cleaning.'
  false;
)

# echo 'So far so good! Testing the build now.'

# npm run build ||
# (
#   echo 'Next build failed: View the errors above to see why.'
#   false;
# )

echo 'All looks good! Committing now.'
