name: All Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SITE_URL: ${{ vars.SITE_URL }}
      GOOGLE_MAP_API_KEY: ${{ vars.GOOGLE_MAP_API_KEY }}
      NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
      NEXTAUTH_SECRET: ${{ vars.NEXTAUTH_SECRET }}
      NEXTAUTH_GITHUB_ID: ${{ vars.NEXTAUTH_GITHUB_ID }}
      NEXTAUTH_GITHUB_SECRET: ${{ vars.NEXTAUTH_GITHUB_SECRET }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: |
          echo "Installing Dependencies..."
          npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.ts
          install-command: npm install --legacy-peer-deps
          build: npm run build
          start: npm start